#!/bin/sh

# make sure you have a `lints` virtualenv and it has:
# pip install flake8

# Warnings to ignore
IGNORES="E501,E401,E124,E126,E127,E128"

source $WORKON_HOME/lints/bin/activate
flake8 --ignore=$IGNORES $*
